### ISSUE TITLE
DaprClient in JS throws DaprClient throws error saying ECONNREFUSED under load condition

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/js-sdk#123] opened 2021-10-19 17:25 UTC
## Expected Behavior

We are using DaprClient to publish message to kafka using kafka pubsub.  
We are receiving http request in our application via dapr side car and in the application we are publishing the message to kafka pub sub using DaprClient. DaprClient should publish the message to kafka pub sub when rate of publishing to kafka is increased. 

## Actual Behavior
DaprClient throws error when the rate at which we publish the message increases. 

We get an error from DarpClient
ERROR 14:43:36:777 error publishing topic through dapr:  FetchError: request to http://localhost:3500/v1.0/publish/kafka-pubsub/request-topic failed, reason: connect ECONNREFUSED 127.0.0.1:3500
== APP ==     at ClientRequest.<anonymous> 

When the rate at which we are publishing the message to kafka pub sub increase than DaprClient throws error saying connection refused.

## Steps to Reproduce the Problem

We are using DaprCLient and publishing using below

```javascript
 async publishMessage(topic: string, message: PubSubMessage): Promise<void> {
    try {
      await this.client.pubsub.publish(this.pubsubName, topic, message);
    } catch (error: any) {
      logger.error("error publishing topic through dapr: ", error);
    }
  }
```

yaml for binding is

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "localhost:9092"
  - name: consumerGroup # Optional. Used for input bindings.
    value: "group1"
  - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
    value: "my-dapr-app-id"
  - name: authRequired # Required.
    value: "false"
 ```

It is running on Mac M1

**Comment by prtk-fyndna** [comment] 2021-11-01 10:25
Hi @XavierGeerinck ,
I have created a sample [project](https://github.com/prtk-fyndna/dapr-pubsub) to reproduce the issue. 

- The project uses [fastify](https://www.fastify.io/) server to expose a `/target` endpoint

- It receives a POST request and asynchronously publishes the request body to kafka using dapr's js-sdk

The entry point for project is `index.ts`, and the usage steps are specified in the project [readme](https://github.com/prtk-fyndna/dapr-pubsub/blob/master/readme.md). I am adding a few code snippets here:

**publishing message**

```typescript
async function publishMessageWithDapr(message: string) {
  await daprClient.pubsub.publish("kafka-pubsub", "test-topic", {
    message: message,
  });
}
//useAxios is false by default
const publishMessage = useAxios ? publishMessageWithAxios : publishMessageWithDapr;
```

**receiving POST request on endpoint** 
```typescript
server.post<requestTemplate>("/target", async (req, res) => {
  const message = req.body.message;
  //asynchronous call
  publishMessage(message).catch((error) => {
    console.error("error publishing message", error);
  });
  res.send("OK");
});

```

On load testing (`500 req/sec across 500 connections for 10 seconds`) the sample project using [autocannon](https://github.com/mcollina/autocannon), I get the following error: 

**autocannon command:** 

```bash
autocannon -c 500 -d 10 -r 1 -m POST  -H 'Content-Type: application/json' -b '{"message":"test-message"}' localhost:3500/v1.0/invoke/test-app/method/target
```

**error**
```bash
== APP == error publishing message FetchError: request to http://localhost:3500/v1.0/publish/kafka-pubsub/test-topic failed, reason: connect ECONNRESET 127.0.0.1:3500
== APP ==     at ClientRequest.<anonymous> (/Users/prtk/Work/dapr-pubsub-issue/dapr-pubsub/node_modules/node-fetch/lib/index.js:1483:11)
== APP ==     at ClientRequest.emit (node:events:390:28)
== APP ==     at Socket.socketErrorListener (node:_http_client:447:9)
== APP ==     at Socket.emit (node:events:390:28)
== APP ==     at emitErrorNT (node:internal/streams/destroy:157:8)
== APP ==     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
== APP ==     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
== APP ==   type: 'system',
== APP ==   errno: 'ECONNRESET',
== APP ==   code: 'ECONNRESET'
== APP == }
```

I also noticed that if I explicitly use an http-client (with its http-agent's max-sockets limit set) to publish messages to kafka instead of using dapr js-sdk APIs,  I don't get the connection reset errors. 
This can be tested by setting `useAxios` variable in [index.ts](https://github.com/prtk-fyndna/dapr-pubsub/blob/master/src/index.ts) as `true`, and re-building the project, before dapr run command.

**Comment by XavierGeerinck** [comment] 2021-11-02 09:23
Hi @prtk-fyndna 

Thanks a lot for the reproduction details! I will dive deeper in it as soon as possible, but first I need to discuss parts with the Dapr team so this might take a bit longer.

Adding @yaron2 here as well for his thoughts

**Comment by XavierGeerinck** [comment] 2021-11-03 08:11
Hi @prtk-fyndna,

The internal SDK translates the calls towards HTTP requests, rather than doing this directly it ensures the Dapr sidecar is ready to interact with. Internally it doesn't use Axios though.

Now if I see this correctly, you are sending the Autocannon to port `3500` which is the Dapr sidecar itself. It doesn't utilize the Dapr JS SDK. How are you testing this with the `publishMessage` method?

Normally this could mean that the Dapr sidecar requires an upscale and you would increase the pods to handle the load on it.

**Comment by prtk-fyndna** [comment] 2021-11-03 08:51
Hi @XavierGeerinck , thanks for your reply. 
You are correct, I am using autocannon to make the http call to `target` endpoint, directly through dapr sidecar and not through dapr sdk.
But the Connection reset error comes while publishing the message to kafka (and not during service invocation) which is done through dapr's js-sdk.

So the flow is : 
1. Autocannon sends request to dapr sidecar which forwards it to `target` endpoint exposed by fastify server

2. The callback method for handling this request is specified in `index.ts` which uses `publishMessage` method to publish message to kafka
```typescript
server.post<requestTemplate>("/target", async (req, res) => {
  const message = req.body.message;
  //asynchronous call
  publishMessage(message).catch((error) => {
    console.error("error publishing message", error);
  });
  res.send("OK");
});
```

3. `publishMessage` is resolved as `publishMessageWithDapr` when the boolean flag `useAxios` is set to `false` (default behaviour).
```typescript
const publishMessage = useAxios ? publishMessageWithAxios : publishMessageWithDapr;
```

4.  `publishMessageWithDapr` uses dapr sdk (`dapr-client` npm library) to publish messages to kafka.

```typescript
//DaprClient is imported from dapr-client sdk
const daprClient = new DaprClient(daprHost, daprPort);
async function publishMessageWithDapr(message: string) {
  await daprClient.pubsub.publish("kafka-pubsub", "test-topic", {
    message: message,
  });
}
``` 

The specified error is logged in `catch` associated with `publishMessage` method (point 2). 

Hope this makes it a little clearer.

**Comment by rahulpoddar-fyndna** [comment] 2021-11-17 07:24
Dear XavierGeerinck , Please let us know if you need further help in reproducing this issue.

**Comment by XavierGeerinck** [comment] 2021-11-17 08:01
Hi @rahulpoddar-fyndna ! Sorry for the delay, I will look into this ASAP. Currently, actors are having priority due to stability requirements.

**Comment by rahulpoddar-fyndna** [comment] 2021-12-29 03:29
Dear XavierGeerinck ,
Wanted to check if there is any update on this.
Regards,
Rahul

**Comment by XavierGeerinck** [comment] 2021-12-30 08:06
Hi @rahulpoddar-fyndna thank you for waiting on this, apologies for the delay in answering this issue since I am aware on how crucial this is. I have checked into this and below are my results for `useAxios` on `false` and `true` respectively.

I can see the issue arises for me for both use cases, I am investigating deeper in if this is due to the SDK or potentially in the upstream Sidecar

`useAxios = false`

![dapr-issue-base-500-connections](https://user-images.githubusercontent.com/591282/147732403-dedb8dca-1320-46af-a89e-14719a6bacaf.png)
![dapr-issue-base-500-connections-2](https://user-images.githubusercontent.com/591282/147732409-e27fb936-84a8-4ee6-8fd2-ca9058fc85b9.png)


`useAxios = true`

![dapr-issue-axios-500-connections](https://user-images.githubusercontent.com/591282/147732414-ee2ebf60-77ae-427f-b4d3-41b719fbbff5.png)
![dapr-issue-axios-500-connections-2](https://user-images.githubusercontent.com/591282/147732418-73633039-be25-49d0-855a-7db5c3ddec16.png)

**Comment by XavierGeerinck** [comment] 2021-12-30 08:55
I have added a Load Test that publishes 2500 messages to `EMQX` as quickly as possible without any issues arising. Could you please check if your same issue arises with EMQX? 

Currently thinking that the Dapr Sidecar and Kafka connection are not able to process quickly enough and start refusing the requests.

**Comment by rahulpoddar-fyndna** [comment] 2022-01-04 02:28
Dear XaviewGeerinck, Thank you for the response. We are testing with kafka, do not have EMQX in our set up.
Another point to note is that while testing with java DaprClient, we did not face this issue. So looks like issue with NodeJS daprclient.

**Comment by rahulpoddar-fyndna** [comment] 2022-02-07 10:14
Dear @XavierGeerinck , Any further updates on this. Now we are facing similar issue with Java SDK as well. When the rate at which the messages are published increases we are getting error in java sdk as well.


2022-02-07 05:55:44.735 ERROR 1 --- [lt-executor-554] c.f.g.pubsub.dapr.DaprPubSubSubscriber   : Throwable occurred while publishing data to Kafka using Dapr

io.dapr.exceptions.DaprException: UNAVAILABLE: io exception
at io.dapr.exceptions.DaprException.propagate(DaprException.java:168)
at io.dapr.client.DaprClientGrpc$2.onError(DaprClientGrpc.java:726)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
... 11 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:535)
... 10 common frames omitted
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer

**Comment by XavierGeerinck** [comment] 2022-02-07 13:09
Hi there! Thanks a lot for providing this. This seems to be indeed as previously said more related to the sidecar scale.

Could you make an issue in the dapr/dapr repository linking to this one?

**Closed as completed** 2022-02-15 16:27 UTC
