### ISSUE TITLE
pub-sub example: fail to run "Cannot find module"

### ISSUE THREAD

**Issue by yosiat** [dapr/js-sdk#129] opened 2021-11-02 18:56 UTC
## Error

When running pub-sub example I am getting this error -
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../../../proto/dapr/proto/runtime/v1/dapr_pb'
Require stack:
- /Users/yosi/code/dapr-js-sdk/build/implementation/Client/GRPCClient/binding.js
- /Users/yosi/code/dapr-js-sdk/build/implementation/Client/DaprClient.js
- /Users/yosi/code/dapr-js-sdk/build/index.js
- /Users/yosi/code/dapr-js-sdk/examples/pubsub/dist/index.js
```

## Steps to Reproduce the Problem

```
> git clone  git clone git@github.com:dapr/js-sdk.git dapr-js-sdk
> cd dapr-js-sdk
> npm install
> npm run build
> cd examples/pubsub
> npm install
>  npm run start:dapr-http
```

## Workaround

I changed the `dapr-client` dependency to come from npm instead of relative file

Environment info:
- node version: 14.18.1
- npm version: 6.14.15

Using dapr installed via homebrew -
```
CLI version: 1.4.0
Runtime version: 1.4.3
```

**Comment by XavierGeerinck** [comment] 2021-11-03 07:30
Hi @yosiat !

I just tried running with the steps you provided to reproduce the problem but I could not reproduce it. I switched to node 14.18.1 as well.

Could you try this again with a clean folder? Does the proto path exist if you look into the build folder? (`build/proto/dapr/proto` should exist)

**Comment by yosiat** [comment] 2021-11-03 08:57
@XavierGeerinck tried in new repo and still don't have this build/proto directory. 
```
dapr-js-sdk on  master [!] is 📦 v1.0.2 ❯ ls build
actors  dapr  enum  google  implementation  index.d.ts  index.js  interfaces  package.json  README.md  types  utils
```

in `build/dapr` there is proto directory
```
dapr-js-sdk on  master [!] is 📦 v1.0.2 ❯ ls build/dapr/proto/
common  runtime
```

**Comment by XavierGeerinck** [comment] 2021-11-03 09:26
@yosiat and you ran the `npm run build` correctly? Does it execute the shell script correctly? 

Are you running this on Windows?

**Comment by yosiat** [comment] 2021-11-03 09:36
@XavierGeerinck running on mac (bigsur, 11.6)

this is the output of `npm run build` -
```
> dapr-client@1.0.2 build /Users/yosi/code/dapr-js-sdk
> ./scripts/build.sh

=====================================================
==================== Dapr JS SDK ====================
=====================================================
Executing in /Users/yosi/code/dapr-js-sdk
Description: Build the package in build/
=====================================================
Preparing Build
Building Library
Preparing Publish
```

**Comment by yosiat** [comment] 2021-11-03 09:51
Found the issue - https://github.com/dapr/js-sdk/blob/master/scripts/build.sh#L31

We are doing - `cp -R ./src/proto/ ./build`

In mac, it copies the contents of `./src/proto` to `build` directory, while in linux (tested on popos) it copies the `proto` folder to `build`.

```
js-sdk on  master [!] is 📦 v1.0.2 ❯ ls build
js-sdk on  master is 📦 v1.0.2 ❯ cp -R ./src/proto/ ./build
js-sdk on  master is 📦 v1.0.2 ❯ ls build
dapr  google
```

As you can see, there is no `proto` directory, there are dapr & google which are contents of src/proto

If I removed the `/` (`./src/proto/` -> `./src/proto`) it works correctly -

```
js-sdk on  master is 📦 v1.0.2 ❯ rm -rf build/*
zsh: sure you want to delete all 2 files in /Users/yosi/code/dapr/js-sdk/build [yn]? y
js-sdk on  master is 📦 v1.0.2 ❯ cp -R ./src/proto ./build
js-sdk on  master is 📦 v1.0.2 ❯ ls ./build
proto
```

To test it works correctly, did the change in scripts/build.sh and now the example is working 🎉

**Comment by XavierGeerinck** [comment] 2021-11-03 10:24
Thanks a lot for your PR! I will close this issue then, if there are any more problems feel free to reopen or ping me

**Closed by XavierGeerinck** 2021-11-03 10:24 UTC
