### ISSUE TITLE
"TypeError: Converting circular structure to JSON" while using custom winston logger service

### ISSUE THREAD

**Issue by HCarnegie** [dapr/js-sdk#488] opened 2023-05-04 09:33 UTC
## Expected Behavior

Using a custom winston logger service for the DaprServer object, should not cause an error. 

## Actual Behavior

Following the instruction of the [sdk docs](https://docs.dapr.io/developing-applications/sdks/js/js-logger/#winston-based-logging) to use a custom winston logger service for the DaprServer object, it's going to raise an exception as soon as the DaprServer object is instantiated. 

```
== APP == TypeError: Converting circular structure to JSON
== APP ==     --> starting at object with constructor 'DerivedLogger'
== APP ==     |     property '_readableState' -> object with constructor 'ReadableState'
== APP ==     |     property 'pipes' -> object with constructor 'Array'
== APP ==     |     index 0 -> object with constructor 'File'
== APP ==     --- property 'parent' closes the circle
== APP ==     at JSON.stringify (<anonymous>)
== APP ==     at new HTTPServer (./dapr/js-sdk/examples/http/actor-parking-sensor/node_modules/@dapr/dapr/implementation/Server/HTTPServer/HTTPServer.js:41:66)
== APP ==     at new DaprServer (./dapr/js-sdk/examples/http/actor-parking-sensor/node_modules/@dapr/dapr/implementation/Server/DaprServer.js:80:32)
== APP ==     at start (./dapr/js-sdk/examples/http/actor-parking-sensor/dist/index.js:36:20)
== APP ==     at Object.<anonymous> (./dapr/js-sdk/examples/http/actor-parking-sensor/dist/index.js:91:1)
== APP ==     at Module._compile (node:internal/modules/cjs/loader:1254:14)
== APP ==     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
== APP ==     at Module.load (node:internal/modules/cjs/loader:1117:32)
== APP ==     at Module._load (node:internal/modules/cjs/loader:958:12)
== APP ==     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

## Steps to Reproduce the Problem
using package "@dapr/dapr": "^3.0.0"

I can reproduce the exception by adopting following steps to the [actor-parking-sensor example](https://github.com/dapr/js-sdk/tree/v3.0.0/examples/http/actor-parking-sensor): 

1. Create Winston Logger Service: 
``` Typescript
import { LoggerService } from "@dapr/dapr";
import * as winston from "winston";

export class WinstonLoggerService implements LoggerService {
  private logger;

  constructor() {
    this.logger = winston.createLogger({
      level: 'info',
      format: winston.format.json(),
      defaultMeta: { service: 'user-service' },
      transports: [
        //
        // - Write all logs with importance level of `error` or less to `error.log`
        // - Write all logs with importance level of `info` or less to `combined.log`
        //
        new winston.transports.File({ filename: 'error.log', level: 'error' }),
        new winston.transports.File({ filename: 'combined.log' }),
      ],
    });
  }

  error(message: any, ...optionalParams: any[]): void {
    this.logger.error(message, ...optionalParams);
  }
  warn(message: any, ...optionalParams: any[]): void {
    this.logger.warn(message, ...optionalParams);
  }
  info(message: any, ...optionalParams: any[]): void {
    this.logger.info(message, ...optionalParams);
  }
  verbose(message: any, ...optionalParams: any[]): void {
    this.logger.verbose(message, ...optionalParams);
  }
  debug(message: any, ...optionalParams: any[]): void {
    this.logger.debug(message, ...optionalParams);
  }
}
```
2. import logger on [index.ts](https://github.com/dapr/js-sdk/blob/v3.0.0/examples/http/actor-parking-sensor/src/index.ts)
``` Typescript
import { WinstonLoggerService } from "./logger";
```

3. pass logger instance via options to DaprServer constructor inside the start function:

passing the logger to the clientOptions or to serverOptions --> fails:
``` Typescript 
...
 const winstonLoggerService = new WinstonLoggerService();
  const logger = {
    level: LogLevel.Debug,
    service: winstonLoggerService,
  };

  const clientOptions = {
    daprHost,
    daprPort,
   // logger, // this fails
  };

  const server = new DaprServer({
    serverHost,
    serverPort,
    clientOptions,
   // logger, // this fails
  });
  const client = new DaprClient(clientOptions); 
...
``` 

passing the logger only to the client constructor --> works fine: 
``` Typescript 
...
 const winstonLoggerService = new WinstonLoggerService();
  const logger = {
    level: LogLevel.Debug,
    service: winstonLoggerService,
  };

  const clientOptions = {
    daprHost,
    daprPort,
   // logger, // this fails
  };

  const server = new DaprServer({
    serverHost,
    serverPort,
    clientOptions,
   // logger, // this fails
  });
  const client = new DaprClient({ ...clientOptions, logger }); // this works
...
``` 

The winston logger is a circular structured object and the HTTPServer constructor serializes the options on the constructor: 
[this.logger.debug(`Configured HTTPServer Options: ${JSON.stringify(options)}`);](https://github.com/dapr/js-sdk/blob/ae34854397150715fe440dec831461d70e17d07a/src/implementation/Server/HTTPServer/HTTPServer.ts#LL49C83-L49C84 )

The same behavior can be reproduced when such an object is passed to any actor method. cause the arguments are serialized as well.

**Comment by HCarnegie** [comment] 2023-05-04 09:56
Possible solutions would be: 

1. using a replacer passed to the JSON.stringify() function: 
``` Typescript 
const getCircularReplacer = () => {
  const seen = new WeakSet();
  return (key: any, value: object | null) => {
    if (typeof value === "object" && value !== null) {
      if (seen.has(value)) {
        return;
      }
      seen.add(value);
    }
    return value;
  };
};
... 
this.logger.debug(`Configured HTTPServer Options: ${JSON.stringify(options, getCircularReplacer())}`);
...
```

2. Use the flatted package to resolve circular references: 
``` Typescript 
import { stringify } from 'flatted';
...
this.logger.debug(`Configured HTTPServer Options: ${stringify(options)}`);
...

```

**Comment by shubham1172** [comment] 2023-05-04 12:09
Nice find, @HCarnegie! Another option could be to skip stringify-ing `options.logger.service` altogether? Maybe something like this -

```js
JSON.stringify( that.person, function( key, value) {
  if( key == 'logger') { return logger.level; }
  else {return value;}
})
```
https://stackoverflow.com/a/12659424/4654175

**Comment by shubham1172** [comment] 2023-05-05 05:20
The problem is that JSON does not accept circular references. This data gets serialized to be transported over the HTTP request. If it's indeed circular, it should throw an error IMO because there is no actual representation of this over JSON.

If we try to handle this on our end and say use something like `getCircularReplacer`, it won't be the same data once it goes through serialize and deserialize, thus resulting in "data loss". I'd propose to let these scenarios error out.

**Comment by HCarnegie** [comment] 2023-05-05 05:57
That makes sense. Thanks for pointing this out. 

Is there a way that actor objects could have methods which are not exposed to HTTP Server? Just methods only accessible for local code? E.g. to inject complex objects or functions?

**Comment by XavierGeerinck** [comment] 2023-05-05 06:28
My two cents:

1. We should indeed fix the stringification of the logger and skipp the circular import stringify
2. Won't fix as this is nate to JSON and Javascript, circular references are not supported and are the responsibility of the developer

**Closed** 2024-04-24 06:59 UTC
Labels: bug, good first issue
